maintainer        "Radim Marek"
maintainer_email  "radim@10xengineer.me"
license           "Apache 2.0"
description       "Installs/manage tarsnap dependencies"
version           "0.1.0"
depends           "apt"
